# Bayesian classification

$$
\newcommand\given[1][]{\:#1\mid\:}
\def\*#1{\mathbf{#1}}
\newcommand{\argmin}{\mathop{\mathrm{argmin}}}
\newcommand{\argmax}{\mathop{\mathrm{argmax}}}
$$


Suppose we observe data $\*x = (x_1, ..., x_m)$ of $m$ "features" and we want to assign probabilities to each of $K$ different classes $\{C_1, ..., C_K\}$.

Bayes' theorem allows us to invert this as:

$$
p(C_k \given \*x) = \frac{p(C_k) p(\*x \given C_k)}{p(x)}
$$

In plain English, recall this can be written:

$$
\text{posterior} = \frac{\text{prior} \times \text{likelihood}}{\text{evidence}}
$$

### Bayes classification

We can construct a classifier from this conditional probability with a decision rule. One common rule is to choose the hypothesis (class) that is most probable. This is known as the "maximum a posteriori" or MAP decision rule. Applying this gives us a **Bayes classifier**: a function that assigns the class label $\hat{y} = C_k$, where $k$ is given by:

$$
\argmax_{k \in \{1, ..., K\}} p(C_k) p(\*x \given C_k)
$$

What about the evidence term in the denominator? This is the irrelevant to the classification problem; it is the same for all classes $C_k$.

### Uncertainty estimates

Notice that the MAP decision rule **throws away information**. The most probable class is only one outcome of the Bayesian formulation of the classification problem above. We can also also read off the probabilities of other classes, the odds (or log odds) of the data belonging to one class or another, etc. We will come back to this below.

### Modelling the class likelihoods

How do we go about modelling the class likelihoods $p(\* x \given C_k)$?

In relatively low-dimensional problems, we can infer these using **density estimation** (for example, a histogram-smoothing procedure like kernel density estimation).

If we have many features (if $m$ is large), our models for the likelihoods $p(\*x \given C_k)$ will be high-dimensional. Even with "big data" $n \approx 10^{12}$ or $n \approx 10^{15}$, the number of data points in each hypercube of feature space will decrease exponentially with $m$.


### Exercise: density estimation with scikit-learn

Here we will go about constructing a full Bayesian model for classification for a 3-dimensional problem: the XXX dataset.

In [1]:
from sklearn.datasets import load_diabetes, load_iris, fetch_mldata

In [2]:
iris = load_iris()

In [3]:
print(iris['DESCR'])

Iris Plants Database

Notes
-----
Data Set Characteristics:
    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    :Attribute Information:
        - sepal length in cm
        - sepal width in cm
        - petal length in cm
        - petal width in cm
        - class:
                - Iris-Setosa
                - Iris-Versicolour
                - Iris-Virginica
    :Summary Statistics:

    ============== ==== ==== ======= ===== ====================
                    Min  Max   Mean    SD   Class Correlation
    ============== ==== ==== ======= ===== ====================
    sepal length:   4.3  7.9   5.84   0.83    0.7826
    sepal width:    2.0  4.4   3.05   0.43   -0.4194
    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
    petal width:    0.1  2.5   1.20  0.76     0.9565  (high!)
    ============== ==== ==== ======= ===== ====================

    :Missing Attribute Values: None
  

In [4]:
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [5]:
X = iris.data
y = iris.target

In [6]:
iris['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [7]:
from sklearn.neighbors.kde import KernelDensity

In [8]:
kde = KernelDensity()

In [9]:
kde.fit(X)

KernelDensity(algorithm='auto', atol=0, bandwidth=1.0, breadth_first=True,
       kernel='gaussian', leaf_size=40, metric='euclidean',
       metric_params=None, rtol=0)

In [32]:
kde.score_samples?

In [ ]:
kde.

In [10]:
kde.score?

In [11]:
kde.__class__.__bases__

(sklearn.base.BaseEstimator,)

In [12]:
from sklearn.base import BaseEstimator

In [13]:
from sklearn.linear_model import LogisticRegression

In [14]:
def non_special(method_name):
    return not(method_name.startswith('__') and method_name.endswith('__'))

In [15]:
list(filter(non_special, dir(LogisticRegression)))

['_estimator_type',
 '_get_param_names',
 '_predict_proba_lr',
 'decision_function',
 'densify',
 'fit',
 'fit_transform',
 'get_params',
 'predict',
 'predict_log_proba',
 'predict_proba',
 'score',
 'set_params',
 'sparsify',
 'transform']

In [16]:
LogisticRegression.predict_proba??

In [17]:
clf = LogisticRegression()

In [18]:
clf.fit(X, y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [19]:
clf.predict_log_proba??

In [20]:
clf.predict_log_proba(X).shape

(150, 3)

In [21]:
X.shape

(150, 4)

In [22]:
clf.predict??

In [23]:
clf.predict(X)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1,
       1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [24]:
LogisticRegression.score??

In [25]:
from sklearn.svm import SVC

In [26]:
SVC.score??

In [36]:
from sklearn.mixture import GaussianMixture

In [37]:
GaussianMixture??

In [28]:
from sklearn.naive_bayes import GaussianNB, BaseNB

In [29]:
BaseNB??

In [33]:
GaussianNB??

In [61]:
from sklearn.utils.multiclass import unique_labels
from sklearn.utils import check_array, check_X_y

In [65]:
u = unique_labels([1, 2, 1, 3, 5])

In [67]:
find([1, 2, 1, 3, 5], u)

[array([0, 2]), array([1]), array([3]), array([4])]

In [63]:
class BayesClassifier(BaseNB):
    """
    p(C | X) \prop p(X | C) p(C)
    
    Performs classification using MAP and
    also uncertainty estimation based on the full model.
    
    Has two components, both themselves scikit-learn Esimator objects:
    1. density_estimator: p(X | C). A class. This will be instantiated for each class.
       It must have a 'predict_log_proba' method.
       
    2. priors: ndarray of length len(C).
    """
    def __init__(self, density_estimator, priors):
        assert hasattr(density_estimator, 'score_samples')
        self.likelihood_fn = density_estimator
        self.prior = priors
        self.n_classes = len(priors)
        self.conditional_models = {}
        #self.log_likelihoods = np.zeros(self.n_classes)
        
    def fit(self, X, y):
        """
        Fit a model for each class.
        """
        X, y = check_X_y(X, y, ensure_min_samples=2, estimator=self)
        self.classes_ = unique_labels(y)

        indices = find(y, self.classes_)
        for c in range(self.n_classes):
            rows = X[indices[c]]
            est = self.likelihood_fn()
            est.fit(rows)
            self.conditional_models[c] = est
    
    def _joint_log_likelihood(self, X):
        """Compute the unnormalized posterior log probability of X

        I.e. ``log P(c) + log P(x|c)`` for all rows x of X, as an array-like of
        shape [n_classes, n_samples].

        Input is passed to _joint_log_likelihood as-is by predict,
        predict_proba and predict_log_proba.
        """
        #check_is_fitted(self, "classes_")

        X = check_array(X)
        joint_log_likelihood = []
        for i in range(np.size(self.classes_)):
            log_p_c = np.log(self.class_prior_[i])
            log_p_x_given_c = self.conditional_models[i](X)
            joint_log_likelihood.append(log_p_c + log_p_x_given_c)

        joint_log_likelihood = np.array(joint_log_likelihood).T
        return joint_log_likelihood

In [39]:
iris.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [40]:
X = iris['data']
y = iris['target']

In [41]:
unique_y = np.unique(y)

NameError: name 'np' is not defined

In [ ]:
unique_y

In [42]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [43]:
unique_y

NameError: name 'unique_y' is not defined

In [44]:
def find(array1, unique_sorted_values):
    """
    Returns a dict {v1: [index_v1, ..., index_vn], v2: ...} arrays (of different lengths in general)
    of the indices into array1 for each of the unique sorted values.
    
    Example:
    a = np.array([0,0,0,1,1,3,3,3,3,2,2,0])
    unique_sorted_values = [0, 1, 2, 3])
    indices = find(a, unique_sorted_values)
    assert indices[0] == [0, 1, 2, 11]
    assert indices[1] == [3, 4]
    assert indices[2] == [9, 10]
    """
    indices = []
    for i, v in enumerate(unique_sorted_values):
        indices.append((array1 == v).nonzero()[0])
    return indices

In [176]:
np.sort?

In [47]:
import numpy as np

In [48]:
a = np.array([0,0,0,1,1,3,3,3,3,2,2,0])
unique_sorted_values = np.sort(np.unique(a))


In [161]:
find(y, unique_y)

[array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
 array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
        67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83,
        84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),
 array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
        126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
        139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149])]

In [50]:
lik = GaussianMixture

In [130]:
lik.score_samples??

In [131]:
import pandas as pd

In [132]:
pd.Series(y).value_counts()

2    50
1    50
0    50
dtype: int64

In [51]:
import numpy as np
prior = np.array([1,1,1]) / 3

In [56]:
model = BayesClassifier(GaussianMixture, prior)

In [57]:
model.fit(X, y)

In [59]:
dir(model)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_cache',
 '_abc_negative_cache',
 '_abc_negative_cache_version',
 '_abc_registry',
 '_estimator_type',
 '_get_param_names',
 '_joint_log_likelihood',
 'conditional_models',
 'fit',
 'get_params',
 'likelihood_fn',
 'n_classes',
 'predict',
 'predict_log_proba',
 'predict_proba',
 'prior',
 'score',
 'set_params']

In [58]:
model.predict_log_proba(X)

NameError: name 'check_is_fitted' is not defined

In [136]:
model.score(X, y)

ValueError: operands could not be broadcast together with shapes (150,) (3,) 

In [138]:
%debug

> <ipython-input-126-5da33df306e9>(23)predict_log_proba()
     21         log_lik = self.likelihood.score_samples(X)
     22         log_prior = np.log(self.prior)
---> 23         return log_lik + log_prior
     24 
     25     def predict_proba(self, X):

ipdb> log_prior
array([-1.09861229, -1.09861229, -1.09861229])
ipdb> log_prior.shape
(3,)
ipdb> log_lik.shape
(150,)
ipdb> q


In [123]:
model.score(X)

TypeError: score() missing 1 required positional argument: 'y'

In [37]:
from sklearn.model_selection import cross_val_score

In [38]:
cross_val_score(kde, X,  y, scoring='accuracy')

AttributeError: 'KernelDensity' object has no attribute 'predict'

In [32]:
from sklearn.mixture import GaussianMixture

In [16]:
diabetes = fetch_mldata('diabetes')

In [17]:
diabetes.keys()

dict_keys(['DESCR', 'COL_NAMES', 'target', 'data'])

In [20]:
diabetes

{'COL_NAMES': ['label', 'data'],
 'DESCR': 'mldata.org dataset: diabetes',
 'data': array([[   6.      ,  148.      ,   72.      , ...,   33.599998,
            0.627   ,   50.      ],
        [   1.      ,   85.      ,   66.      , ...,   26.6     ,
            0.351   ,   31.      ],
        [   8.      ,  183.      ,   64.      , ...,   23.299999,
            0.672   ,   32.      ],
        ..., 
        [   5.      ,  121.      ,   72.      , ...,   26.200001,
            0.245   ,   30.      ],
        [   1.      ,  126.      ,   60.      , ...,   30.1     ,
            0.349   ,   47.      ],
        [   1.      ,   93.      ,   70.      , ...,   30.4     ,
            0.315   ,   23.      ]]),
 'target': array([-1,  1, -1,  1, -1,  1, -1,  1, -1, -1,  1, -1,  1, -1, -1, -1, -1,
        -1,  1, -1,  1,  1, -1, -1, -1, -1, -1,  1,  1,  1,  1, -1,  1,  1,
         1,  1,  1, -1, -1, -1,  1,  1,  1, -1,  1, -1,  1,  1, -1,  1,  1,
         1,  1, -1,  1,  1, -1,  1,  1,  1,  1, -1,

In [19]:
print(diabetes['COL_NAMES'])

['label', 'data']


### Simplifying assumption for higher dimensions: "Naive" Bayes

A family of classifiers known as **Naive Bayes** simplifies the likelihood model (at the expense of its expressive power) by making the (strong) simplifying assumption of conditional independence:

$$
p(\*x \given C_k) \approx \prod_{i=1}^m p(x_i \given C_k)
$$

In addition, further simplifying assumptions are sometimes made for various problems:
- that discrete binary values (booleans) are generated from **Bernoulli** trials.
- that discrete values representing frequencies of events are distributed according to a **multinomial** distribution (a generalization of the Bernoulli and binomial distributions).
- that continuous values associated with each class are **normally** distributed ("Gaussian").

#### Recall that these assumptions corresponding to certain choices of **prior information** expressed as feature constraints in exponential-family models:

- Bernoulli: constraint $E(K) = p$ for sample space $k \in \{0,1\}$.
- Multinomial: XXXXXX
- Gaussian: constraints on $E(X)$ and $E(X^2)$


#### Examples: scikit-learn